sudo: required
language: cpp
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libboost-all-dev
    - libclhep-dev
    - root-system-bin
    - root-system-common
    - build-essential
    - automake1.11
    - autoconf2.64
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - wget wget http://proj-clhep.web.cern.ch/proj-clhep/DISTRIBUTION/tarFiles/clhep-2.2.0.5.tgz
  - tar xzfv clhep-2.2.0.5.tgz
  - cd 2.2.0.5/CLHEP
  - ./bootstrap
  - ./configure
  - make 
  - sudo make install
  - cd ../../
  - wget http://www-ekp.physik.uni-karlsruhe.de/~sieber/root_5.34.07-1_amd64.deb || exit 1
  - sudo dpkg -i root_5.34.07-1_amd64.deb || exit 1
  - echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf
  - echo "/usr/local/lib/root" | sudo tee -a /etc/ld.so.conf
  - sudo ldconfig || exit 1
install: 
  - cmake .
  - make VERBOSE=1
script: 
  - ./tests/kinematics01
  - ./tests/kinematics02
  - ./tests/kinematics03
  - ./tests/propagatortests
  - ./UnitTests/raveunittests

