sudo: required
language: cpp
notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - root-system
    - libboost-all-dev
install: 
  - cmake .
  - make VERBOSE=1
script: 
  - ./tests/kinematics01
  - ./tests/kinematics02
  - ./tests/kinematics03
  - ./tests/propagatortests
  - ./UnitTests/raveunittests

